### ISSUE TITLE
Crash when I click on activate

### ISSUE THREAD

**Issue by NokisDemox** [draguve/droidducky-app#11]
When im in the executor and i hit acrivate, it crashes, i have my android well set up and i have tested this app in a few devices, all have the same error. I havent manage the app to work :( .
Here is the log from android studio:

`AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.draguve.droidducky, PID: 16287
                  java.lang.NullPointerException
                      at com.draguve.droidducky.DuckConverter.codeToCommand(**DuckConverter.java:90**)
                      at com.draguve.droidducky.DuckConverter.charToCommand(**DuckConverter.java:113**)
                      at com.draguve.droidducky.DuckConverter.stringToCommands(**DuckConverter.java:72**)
                      at com.draguve.droidducky.ExecuterActivity$2.onCheckedChanged(**ExecuterActivity.java:98**)
                      at android.widget.CompoundButton.setChecked(CompoundButton.java:127)
                      at android.widget.ToggleButton.setChecked(ToggleButton.java:73)
                      at android.widget.CompoundButton.toggle(CompoundButton.java:87)
                      at android.widget.CompoundButton.performClick(CompoundButton.java:99)
                      at android.view.View$PerformClick.run(View.java:18422)
                      at android.os.Handler.handleCallback(Handler.java:733)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5017)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                      at dalvik.system.NativeStart.main(Native Method)`

I would like to get it working, because i dont want to have to install kali nethunter to have a rubberducky inside android. I hope you know how to fix it (in bold the lines i can click on).

**Comment by NokisDemox** [comment]
Doesn't show up in bold but between ** **

**Comment by draguve** [comment]
can you also send me the script you were trying to run?

**Comment by NokisDemox** [comment]
I tried a lot of combinations and in different lenguages but all they had the same result. For example `STRING test` or `DELAY 1000
STRING test
ENTER`
or whatever y put, it crashes. I tried in an android 7 rooted, an android 5 rooted and android 4.4 rooted any of them successfully make the activation before runing the code.

**Comment by draguve** [comment]
Ok I have fixed the error there (maybe)
Also you might be pressing the wrong button

You need to press the run button to start the script the other button ,
spins up a http server for file serving

**Comment by NokisDemox** [comment]
Okay thanks, also, the HID patch is on the custom rom or you need to flash a the kernel?

**Comment by draguve** [comment]
The HID patch is a custom kernel 
you can find more about it here https://github.com/pelya/android-keyboard-gadget
